services:
  - type: web
    name: lumina-ai
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://stutxyiqausjicjmofsn.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://luminaai25.netlify.app
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ADMIN_EMAILS
        value: sharanrajithk@gmail.com,madhurahegde475@gmail.com
